version: '3'
volumes:
    pgdata:
        driver: local
services:
    db:
        image: postgres
        ports:
            - "5432"
        environment:
            - POSTGRES_DB=cinema_db
            - POSTGRES_USER=borbaris161
            - POSTGRES_PASSWORD=12345
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/srv/www/TicketReservation
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db