# Generated by Django 2.1.7 on 2019-05-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ticket',
        ),
    ]
