# Generated by Django 2.1.7 on 2019-05-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        ('halls', '0002_add_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSession',
            fields=[
                ('beginning_session', models.TimeField(blank=True, default=None, primary_key=True, serialize=False)),
                ('ending_session', models.TimeField(default=None, null=True)),
                ('ticket_price', models.IntegerField(blank=True, null=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.Film')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='halls.Hall')),
            ],
            options={
                'db_table': 'film_session',
                'ordering': ['beginning_session'],
            },
        ),
    ]
