# Generated by Django 2.1.7 on 2019-05-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_session'),
        ('film_session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsession',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='filmsession',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='tickets.Ticket'),
        ),
    ]
