# Generated by Django 2.1.7 on 2019-05-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_session', '0004_auto_20190507_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsession',
            name='ticket',
            field=models.ForeignKey(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='tickets.Ticket'),
        ),
    ]
