# Generated by Django 2.1.7 on 2019-05-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_session', '0005_auto_20190507_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsession',
            name='ticket',
        ),
    ]
