# Generated by Django 2.1.7 on 2019-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('title', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
    ]
