# Generated by Django 2.1.7 on 2019-04-30 05:20

from django.db import migrations
from ..addhall import *

class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(red),
        migrations.RunPython(green),
        migrations.RunPython(black),
        migrations.RunPython(yellow)
    ]
