# Generated by Django 2.1.7 on 2019-05-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'films',
            },
        ),
    ]
