# Generated by Django 2.1.7 on 2019-05-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190506_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='film_session.FilmSession'),
        ),
    ]
