# Generated by Django 2.1.7 on 2019-05-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190507_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
    ]
