# Generated by Django 2.1.7 on 2019-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='free_place',
            field=models.BooleanField(default=True),
        ),
    ]
