# Generated by Django 2.1.7 on 2019-05-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_session', '0006_remove_filmsession_ticket'),
        ('tickets', '0012_auto_20190507_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_session.FilmSession'),
        ),
    ]
