# Generated by Django 2.1.7 on 2019-05-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_session.FilmSession'),
        ),
    ]
